apiVersion: v1
kind: ConfigMap
metadata:
  name: iot-config
  namespace: {{ .Release.Namespace }}
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  REDIS_HOST: "{{ .Release.Name }}-redis-master"
  REDIS_PORT: "6379"
  POSTGRES_HOST: "{{ .Release.Name }}-db"
  POSTGRES_PORT: "5432"
  TELEMETRY_POSTGRES_HOST: "{{ .Release.Name }}-telemetry-db"
  DEVICE_MANAGER_URL: "http://device-manager:8000"
  TELEMETRY_URL: "http://telemetry-ingestor:8001"
  HISTORICAL_URL: "http://historical-service:8002"
---
apiVersion: v1
kind: Secret
metadata:
  name: iot-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  POSTGRES_USER: "iot_user"
  POSTGRES_PASSWORD: "changeme"
  POSTGRES_DB: "iot_db"
  POSTGRES_DB_TELEMETRY: "iot_telemetry"
  INFLUXDB_URL: "http://influxdb:8086"
  INFLUXDB_TOKEN: "my-super-secret-token"
  INFLUXDB_ORG: "iot-org"
  INFLUXDB_BUCKET: "telemetry"
  BOT_TOKEN: ""
  CHAT_ID: ""
