apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: iot-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.vault.refreshInterval | quote }}
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: iot-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: app
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: app
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_DB
      remoteRef:
        key: app
        property: POSTGRES_DB
    - secretKey: POSTGRES_DB_TELEMETRY
      remoteRef:
        key: app
        property: POSTGRES_DB_TELEMETRY
    - secretKey: DOCKER_INFLUXDB_INIT_USERNAME
      remoteRef:
        key: iot-helm/app
        property: DOCKER_INFLUXDB_INIT_USERNAME
    - secretKey: DOCKER_INFLUXDB_INIT_PASSWORD
      remoteRef:
        key: iot-helm/app
        property: DOCKER_INFLUXDB_INIT_PASSWORD
    - secretKey: INFLUXDB_URL
      remoteRef:
        key: app
        property: INFLUXDB_URL
    - secretKey: INFLUXDB_TOKEN
      remoteRef:
        key: app
        property: INFLUXDB_TOKEN
    - secretKey: INFLUXDB_ORG
      remoteRef:
        key: app
        property: INFLUXDB_ORG
    - secretKey: INFLUXDB_BUCKET
      remoteRef:
        key: app
        property: INFLUXDB_BUCKET
    - secretKey: BOT_TOKEN
      remoteRef:
        key: app
        property: BOT_TOKEN
    - secretKey: CHAT_ID
      remoteRef:
        key: app
        property: CHAT_ID
    - secretKey: INFLUXDB_ADMIN_PASSWORD
      remoteRef:
        key: app
        property: INFLUXDB_ADMIN_PASSWORD
