# --- PostgreSQL main ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-postgresql-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# --- PostgreSQL telemetry ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: telemetry-db-postgresql-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi