apiVersion: v2
name: iot-platform
description: IoT Microservices Platform
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: "15.5.38"
    repository: "https://charts.bitnami.com/bitnami"
    alias: db
  - name: postgresql
    version: "15.5.38"
    repository: "https://charts.bitnami.com/bitnami"
    alias: telemetry-db
  - name: redis
    version: "19.6.4"
    repository: "https://charts.bitnami.com/bitnami"
