# Глобальные настройки образов
image:
  pullPolicy: IfNotPresent
  tag: latest

# Образы микросервисов
services:
  apiGateway:
    image: registry.kube-system.svc.cluster.local:80/iot/api-gateway
    tag: latest
  deviceManager:
    image: registry.kube-system.svc.cluster.local:80/iot/device-manager
    tag: latest
  telemetry:
    image: registry.kube-system.svc.cluster.local:80/iot/telemetry
    tag: latest
  historical:
    image: registry.kube-system.svc.cluster.local:80/iot/historical
    tag: latest
  alertEngine:
    image: registry.kube-system.svc.cluster.local:80/iot/alert-engine
    tag: latest
  automationService:
    image: registry.kube-system.svc.cluster.local:80/iot/automation-service
    tag: latest
  notificationService:
    image: registry.kube-system.svc.cluster.local:80/iot/notification-service
    tag: latest